CONFIG += c++11
CONFIG -= debug_and_release

ROOT_PATH = $$OUT_PWD/../..
BUILD_PATH = $$ROOT_PATH/build
BIN_PATH = $$ROOT_PATH/bin

DESTDIR = $$BIN_PATH
OBJECTS_DIR = $$BUILD_PATH/$$TARGET/obj
MOC_DIR = $$BUILD_PATH/$$TARGET/moc
RCC_DIR = $$BUILD_PATH/$$TARGET/rcc
UI_DIR = $$BUILD_PATH/$$TARGET/ui
#MAKEFILE = $$BUILD_PATH/$$TARGET/Makefile
